[general]
save_aggregate = True
save_forensic = True
output = /output/
log_file = /dev/stdout

# IMAPの代わりに mailbox watch / delete を設定
[mailbox]
watch = True
delete = False
## label or folder path(事前にラベル分類設定とdmarc-archiveラベルは作成してください。または既存のラベル名に変更してください
reports_folder = dmarc-reports-rua
archive_folder = dmarc-archive

since = 2w

# Gmail API 専用ブロックを追加
[gmail_api]
credentials_file = /etc/parsedmarc/credentials.json
# Pre-generated token (see generate_token.py). Bind-mounted from the host.
token_file = /etc/parsedmarc/token.json
scopes = https://www.googleapis.com/auth/gmail.modify
paginate_messages = True

[elasticsearch]
hosts = elasticsearch:9200
ssl = False
